### ISSUE TITLE
Appearance of the GTK2 front-end

### ISSUE THREAD

**Issue by micrococo** [lxde/lx-control-center#2]
Hi.

The horizontal scroll bar is always visible in the GTK2 front-end. The GTK3 front-end doesn't behaves the same. In addition, the controls in Preferences are stretched to fill all the horizontal space. I don't know if it is a design decision but in the GTK3 front-end controls are left aligned and have a sane size.

Greetings.

**Comment by gilir** [comment]
Hi,

Thanks for the report. Yes, it's 2 bugs in the GTK2 frontend, it should behave like the GTK3 one.

**Comment by gilir** [comment]
I think the git version is a bit more sane now for both GTK2 and GTK3 frontends. However, I trying to improve the way widgets are displayed for preferences and modules, so the behavior may change in the future.
I'm closing the bug now, but feel free to re-open if it's not fixed for you.
